# Generated by Django 3.2.9 on 2022-03-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MegaSenaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.IntegerField(verbose_name='Concurso')),
                ('date', models.DateField(verbose_name='Data')),
                ('orb_1', models.IntegerField(verbose_name='Bola 1')),
                ('orb_2', models.IntegerField(verbose_name='Bola 2')),
                ('orb_3', models.IntegerField(verbose_name='Bola 3')),
                ('orb_4', models.IntegerField(verbose_name='Bola 4')),
                ('orb_5', models.IntegerField(verbose_name='Bola 5')),
                ('orb_6', models.IntegerField(verbose_name='Bola 6')),
            ],
        ),
    ]
