# Generated by Django 3.2.9 on 2022-03-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megasena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megasenamodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='megasenamodel',
            name='contest',
            field=models.IntegerField(primary_key='true', serialize=False, verbose_name='Concurso'),
        ),
    ]
