# Generated by Django 3.2.9 on 2022-03-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megasena', '0002_auto_20220308_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='megasenamodel',
            options={'verbose_name': 'Sorteio'},
        ),
        migrations.AlterField(
            model_name='megasenamodel',
            name='contest',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Concurso'),
        ),
    ]
