# Generated by Django 3.2.9 on 2022-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(help_text='Digite aqui o nome do grupo do produto', max_length=50),
        ),
    ]
