# Generated by Django 3.2.9 on 2022-02-25 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_groupproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, help_text='Id do grupo de um produto', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
    ]
