# Generated by Django 3.2.9 on 2022-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220225_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='Id do grupo de um produto', primary_key=True, serialize=False, unique=True),
        ),
    ]
