# Generated by Django 3.2.9 on 2022-02-25 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_groupproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='id',
            field=models.IntegerField(auto_created=True, default=uuid.uuid4, help_text='Id do grupo de um produto', primary_key=True, serialize=False, unique=True),
        ),
    ]
