# Generated by Django 3.2.9 on 2022-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_groupproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
