# Generated by Django 3.2.9 on 2022-02-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_groupproduct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='', help_text='Nome do produto', max_length=80, verbose_name='Nome do produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço do produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.groupproduct', verbose_name='Grupo do produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.TextField(default='', help_text='Quantidade de unidades do produto', max_length=15, verbose_name='Unidades do produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='active',
            field=models.BooleanField(verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(help_text='Digite aqui o nome do grupo do produto', max_length=50, verbose_name='Nome do grupo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
