# Generated by Django 3.2.9 on 2022-02-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220225_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nome do produto', max_length=80, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(help_text='Quantidade de unidades do produto', max_length=15, verbose_name='Unidades do produto'),
        ),
    ]
