# Generated by Django 3.2.9 on 2022-02-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20220225_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Preço do produto'),
        ),
    ]
