# Generated by Django 3.2.9 on 2022-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20220225_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default='', help_text='Identificador Único para a companhia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='mail',
            field=models.CharField(default='', help_text='Email da companhia', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', help_text='Nome da companhia', max_length=80, verbose_name='Nome da companhia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', help_text='Telefone da companhia', max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(default='', help_text='Site da companhia', max_length=100, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(default='', help_text='Digite aqui o nome do grupo do produto', max_length=50, verbose_name='Nome do grupo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', help_text='Nome do produto', max_length=80, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default=0, help_text='Quantidade de unidades do produto', max_length=15, verbose_name='Unidades do produto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(default='', help_text='Última atualização sobre o produto no estoque'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Quantidade do produto no estoque'),
        ),
    ]
