# Generated by Django 3.2.9 on 2022-02-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20220225_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.TextField(default='', help_text='Identificador Único para a companhia', max_length=5, primary_key=True, serialize=False),
        ),
    ]
