# Generated by Django 3.2.9 on 2022-02-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_company_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companhia', 'verbose_name_plural': 'Companhias'},
        ),
    ]
