# Generated by Django 3.2.9 on 2022-02-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.TextField(default='', help_text='Identificador Único para a Empresa', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='mail',
            field=models.CharField(default='', help_text='Email da Empresa', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', help_text='Nome da Empresa', max_length=80, verbose_name='Nome da companhia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', help_text='Telefone da Empresa', max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(default='', help_text='Site da Empresa', max_length=100, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.company', verbose_name='Empresa'),
        ),
    ]
