# Generated by Django 3.2.9 on 2022-02-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_groupproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproduct',
            options={'verbose_name': 'Grupo de um produto', 'verbose_name_plural': 'Grupos de Produtos'},
        ),
    ]
