# Generated by Django 3.2.9 on 2022-02-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_groupproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default='', help_text='Identificador Único para a Empresa', max_length=5, primary_key=True, serialize=False),
        ),
    ]
