# Generated by Django 3.2.9 on 2022-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
