# Generated by Django 3.2.9 on 2022-02-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20220225_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Preço do produto'),
        ),
    ]
